/**
 * Standalone schema migration runner for Docker deployments.
 * Uses the pg client directly (available in production node_modules via pnpm deploy).
 * Reads SQL files generated by drizzle-kit generate and applies them in order,
 * tracking applied migrations in a __drizzle_migrations table.
 */
import pg from "pg";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

const { Client } = pg;

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) {
  console.error("ERROR: DATABASE_URL is not set");
  process.exit(1);
}

const MIGRATIONS_DIR = "/app/migrations";

async function runMigrations() {
  const client = new Client({ connectionString: DB_URL });

  try {
    await client.connect();
    console.log("[migrate] Connected to database");

    // Tracking table — matches the format drizzle-orm's migrate() uses
    await client.query(`
      CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
        id        SERIAL PRIMARY KEY,
        hash      TEXT   NOT NULL UNIQUE,
        created_at BIGINT
      )
    `);

    const files = (await readdir(MIGRATIONS_DIR).catch(() => []))
      .filter((f) => f.endsWith(".sql"))
      .sort();

    if (files.length === 0) {
      console.log("[migrate] No migration files found — skipping");
      return;
    }

    for (const file of files) {
      const existing = await client.query(
        'SELECT id FROM "__drizzle_migrations" WHERE hash = $1',
        [file]
      );
      if (existing.rows.length > 0) {
        console.log(`[migrate] Already applied: ${file}`);
        continue;
      }

      const sql = await readFile(path.join(MIGRATIONS_DIR, file), "utf-8");
      // Split on drizzle-kit statement separators and run each statement
      const statements = sql
        .split("--> statement-breakpoint")
        .map((s) => s.trim())
        .filter(Boolean);

      for (const stmt of statements) {
        await client.query(stmt);
      }

      await client.query(
        'INSERT INTO "__drizzle_migrations" (hash, created_at) VALUES ($1, $2)',
        [file, Date.now()]
      );
      console.log(`[migrate] Applied: ${file}`);
    }

    console.log("[migrate] All migrations complete");
  } finally {
    await client.end();
  }
}

runMigrations().catch((err) => {
  console.error("[migrate] FAILED:", err.message);
  process.exit(1);
});
