// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sogram/Analytics.tsx": () => import("../components/mockups/sogram/Analytics.tsx"),
  "./components/mockups/sogram/CopyTrading.tsx": () => import("../components/mockups/sogram/CopyTrading.tsx"),
  "./components/mockups/sogram/Feed.tsx": () => import("../components/mockups/sogram/Feed.tsx"),
  "./components/mockups/sogram/TraderProfile.tsx": () => import("../components/mockups/sogram/TraderProfile.tsx")
};
